=== GeoscienceAustralia/samples-api/xml-validation/igsn-csiro-v2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 (x64) (http://www.altova.com) by Terry Rankine (CSIRO) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink/namespace" xmlns:igsn="http://igsn.org/schema/kernel-v.1.0" targetNamespace="http://igsn.org/schema/kernel-v.1.0" elementFormDefault="qualified" version="2.0">
	<xs:include schemaLocation="include/igsn-nameIdentifierScheme-v1.0.xsd"/>
	<xs:include schemaLocation="include/igsn-identifierType-v1.0.xsd"/>
	<xs:include schemaLocation="include/igsn-relatedIdentifierType-v1.0.xsd"/>
	<xs:include schemaLocation="include/igsn-relationType-v1.0.xsd"/>
	<xs:include schemaLocation="include/igsn-eventType-v1.0.xsd"/>
	<xs:include schemaLocation="include/igsn-dateType.xsd"/>
	<xs:include schemaLocation="include/igsn-sampleType.xsd"/>
	<xs:include schemaLocation="include/igsn-samplingFeature.xsd"/>
	<xs:include schemaLocation="include/igsn-materialType.xsd"/>
	<xs:include schemaLocation="include/igsn-spatialType.xsd"/>
	<xs:include schemaLocation="include/igsn-nillType.xsd"/>
	<!-- xs:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/basicTypes.xsd"/ -->
	<!-- xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance"/ -->
	<xs:import/>
	<xs:import/>
	<xs:element name="samples">
		<xs:annotation>
			<xs:documentation>A collection of samples.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<!--xs:element name="subNamespace" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>The subnamespace of the data center registering the samples</xs:documentation>
					</xs:annotation>
				</xs:element -->
				<xs:element name="sample" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>An individual sample</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:all>
							<xs:element name="sampleNumber">
								<xs:annotation>
									<xs:documentation>(Required)The first two characters must be [A-Z] and represents the namespace of an allocating agent, e.g, CS. The rest can be a combination of characters, numbers and dash (-) and dot(.). See IGSN syntax at http://dokuwiki.gfz-potsdam.de/datawiki/doku.php?id=igsn:syntax</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="igsn:igsnSyntax">
											<xs:attribute name="identifierType" type="igsn:identifierType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<!-- model number, e.g., igsn -->
							<xs:element name="sampleName">
								<xs:annotation>
									<xs:documentation>Name of the sample.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="otherNames" minOccurs="0">
								<xs:annotation>
									<xs:documentation>An alias for the sample name. Use this element to include local name/identifier of the sample.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="otherName" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="isPublic">
								<xs:annotation>
									<xs:documentation>The visibility of sample metadata. Use 1 for public and 0 for private samples.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:boolean"/>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="landingPage">
								<xs:annotation>
									<xs:documentation>The landing page of a sample.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:anyURI">
										<xs:pattern value="https?://.+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sampleTypes" nillable="true">
								<xs:annotation>
									<xs:documentation>The basic form of a sample. See controlled list "include/igsn-sampleType.xsd". If the value of a sampleType is not available, declare the xsi:nil and nilReason attributes, e.g.,  xsi:nil="true" nilReason=""</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="sampleType" type="igsn:sampleType" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attributeGroup ref="igsn:nullValue"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="materialTypes" nillable="true">
								<xs:annotation>
									<xs:documentation>The materials that compose a sample. See controlled list "include/igsn-materialType.xsd"</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="materialType" type="igsn:materialType" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attributeGroup ref="igsn:nullValue"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="classification" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Classification concepts, e.g. Rock>Igneous.Use the classifictionIdentifier attibute to indicate the URL of the concept or related vocabulary service.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:token">
											<xs:attribute name="classificationIdentifier" type="xs:anyURI"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="purpose" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The purpose for collecting the sample.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="samplingLocation" nillable="true">
								<xs:annotation>
									<xs:documentation>The location where the sample is collected. This may apply to geo (latlon,localxy, bounding box(bbox)) and non-geo(locality) location information.Example of latitude and longitude: 51.150719,-0.973177. Example of localxy (UTM Easting and UTM Northing) is : 641753.82,5668538.64. The srs attribute can be used to indicate the UTMZone (e.g., 30U) or SRID. If the location value is not available, declare the xsi:nil and nilReason attributes.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:group ref="igsn:locationGroup">
										<xs:annotation>
											<xs:documentation>
			</xs:documentation>
										</xs:annotation>
									</xs:group>
									<xs:attributeGroup ref="igsn:nullValue"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingTime" nillable="true">
								<xs:annotation>
									<xs:documentation>The temporal information of sample collection. </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:group ref="igsn:timeGroup"/>
									<xs:attributeGroup ref="igsn:nullValue"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingFeatures" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The host from which a sample is collected/produced, e.g., observation well. See controlled list - "include/igsn-samplingFeature-v1.1.xsd". Note that this is not ultimate feature (sampledFeature),but rather referring to the proximate feature of a sample.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="samplingFeature" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="samplingFeatureName">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="samplingFeatureType" type="igsn:samplingFeature"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="samplingFeatureLocation" minOccurs="0">
														<xs:complexType>
															<xs:group ref="igsn:locationGroup">
																<xs:annotation>
																	<xs:documentation>The location of a samplingfeature. This may apply to geo (latlon,localxy, bounding box(bbox)) and non-geo(locality) location information. Example of latitude and longitude: 51.150719,-0.973177. Example of localxy (UTM Easting and UTM Northing) is : 641753.82,5668538.64. The srsName attribute can be used to indicate the UTMZone (e.g., 30U) or SRID.
			</xs:documentation>
																</xs:annotation>
															</xs:group>
														</xs:complexType>
													</xs:element>
													<xs:element name="sampledFeatures" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="sampledFeature" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:token">
																				<xs:attribute name="sampledFeatureType" type="xs:anyURI"/>
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="sampleCollectors" nillable="true">
								<xs:annotation>
									<xs:documentation>Contact information of the person who collected the sample.This also applies to the principal investigator in a project responsible for sample collection.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="collector" maxOccurs="unbounded">
											<!--xs:complexType>
												<xs:simpleContent>
													<xs:extension base="igsn:StringOrNillValues">
														<xs:attribute name="collectorIdentifier" type="xs:anyURI" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType -->
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:token">
														<xs:attribute name="collectorIdentifier" type="xs:anyURI" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="igsn:nullValue"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingMethod" nillable="true">
								<xs:annotation>
									<xs:documentation>Method/equipment used to collect the sample, e.g., Dredging, Manual Observation. </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:token">
											<xs:attributeGroup ref="igsn:nullValue"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingCampaign" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The field program/related projects.  e.g., cruise or expedition.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sampleCuration" nillable="false">
								<xs:annotation>
									<xs:documentation>Sample archival information. The curator information must be specified. This can be present or future curator.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="curation" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="curator" type="xs:token"/>
													<xs:element name="curationTime" minOccurs="0">
														<xs:annotation>
															<xs:documentation>The temporal information of sample curation</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:group ref="igsn:timeGroup"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="curationLocation" type="xs:token" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="relatedResources" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>This element is used to link the sample metadata other related samples and documents (e.g., project reports, publications, etc.)</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="relatedResourceIdentifier" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:token">
														<xs:attribute name="relatedIdentifierType" type="igsn:relatedIdentifierType"/>
														<xs:attribute name="relationType" type="igsn:relationType"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="comments" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Any free text describing the sample. This also can be used to include additional metadata which cannot be specified with this standard schema.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="logElement" nillable="false" minOccurs="1" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>The type of status of the physical sample and IGSN registration</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:token">
											<xs:attribute name="event" type="igsn:eventType" use="required"/>
											<xs:attribute name="timeStamp" type="igsn:W3CDTFdate" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="timeGroup">
		<xs:annotation>
			<xs:documentation>Represents time instant or time period (start,end).</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="timeInstant" type="igsn:W3CDTFdate" minOccurs="0" maxOccurs="1"/>
			<xs:element name="timePeriod" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="start" type="igsn:W3CDTFdate" minOccurs="0"/>
						<xs:element name="end" type="igsn:W3CDTFdate" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:group>
	<xs:group name="locationGroup">
		<xs:annotation>
			<xs:documentation>This may apply to a named place (locality) or geometric (coordinate-based) location, e.g., WKT representation. The srs attribute indicates a Spatial Reference System Identifier (SRID)/EPSG, e.g., EPSG:4326
			</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="locality" type="xs:token" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Named place or address</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="wkt" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Well Known Text (wkt) representation of entity. </xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="srs" type="xs:token" use="required">
								<xs:annotation>
									<xs:documentation>Use EPSG code, e.g., "EPSG:XXX", where "XXX" is the EPSG code for the referenced coordinate system; "none" shall be provided if the coordinate system is unreferenced.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="spatialType" type="igsn:spatialType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="elevation" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Height of an entity above datum.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="datum" type="xs:token" use="optional">
								<xs:annotation>
									<xs:documentation>a vertical datums specify the origin for elevations assocated with a feature, e.g., MSL, NAVD88, NGVD29, or Unknown</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="units" type="xs:token" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:group>
	<xs:attributeGroup name="nullValue">
		<xs:attribute name="nilReason" type="igsn:NilReasonType" use="optional"/>
	</xs:attributeGroup>
	<xs:simpleType name="igsnSyntax">
		<xs:annotation>
			<xs:documentation>IGSN syntax data type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="([A-Z]{2}[A-Za-z0-9\-.]+)"/>
		</xs:restriction>
	</xs:simpleType>
	<!--- xs:simpleType name="trueOrFalse">
		<xs:restriction base="xs:boolean">
			<xs:pattern value="0"/>
			<xs:pattern value="1"/>
		</xs:restriction>
	</xs:simpleType -->
	<!--xs:simpleType name="StringOrNillValues">
		<xs:union memberTypes="xs:anyURI igsn:NilReasonType"/>
	</xs:simpleType -->
</xs:schema>

=== GeoscienceAustralia/samples-api/test/sample_eg3_IGSN_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<igsn:samples
		xsi:schemaLocation="http://igsn.org/schema/kernel-v.1.0 ../xml-validation/igsn-csiro-v2.0.xsd"
		xmlns:igsn="http://igsn.org/schema/kernel-v.1.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<!-- from https://github.com/kitchenprinzessin3880/csiro-igsn-schema/blob/master/example-capricon.xml -->
    <!--igsn:subNamespace>CAP</igsn:subNamespace -->
	<igsn:sample>
		<igsn:sampleNumber identifierType="igsn">CSCAP0001</igsn:sampleNumber>
		<igsn:sampleName>Cap0001-JHP8</igsn:sampleName>
		<igsn:isPublic>1</igsn:isPublic>
		<igsn:landingPage><![CDATA[https://capdf.csiro.au/gs-hydrogeochem/public/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=public:hydrogeochem&cql_filter=sid%3D243]]></igsn:landingPage>
		<igsn:sampleTypes>
			<igsn:sampleType>http://vocabulary.odm2.org/specimentype/precipitationBulk</igsn:sampleType>
		</igsn:sampleTypes>
		<igsn:materialTypes>
			<igsn:materialType>http://vocabulary.odm2.org/medium/snow</igsn:materialType>
		</igsn:materialTypes>
		<igsn:samplingLocation/>
		<igsn:samplingTime/>
		<igsn:sampleCuration>
			<igsn:curation> <!-- nick -->
				<igsn:curator>Mineral Resources Flagship,CSIRO</igsn:curator>
                <igsn:curationLocation>Some location</igsn:curationLocation>
			</igsn:curation> <!-- nick -->
		</igsn:sampleCuration>
        <igsn:classification>rock</igsn:classification>
        <igsn:comments>This is a fake comment</igsn:comments>
        <igsn:otherNames>
            <igsn:otherName>FakeOtherName</igsn:otherName>
        </igsn:otherNames>
        <igsn:purpose>Fake purpose</igsn:purpose>
        <igsn:samplingFeatures>
            <igsn:samplingFeature>
                <igsn:samplingFeatureName>mountain X</igsn:samplingFeatureName>
            </igsn:samplingFeature>
        </igsn:samplingFeatures>
        <igsn:sampleCollectors>
            <igsn:collector>Nick Car</igsn:collector>
        </igsn:sampleCollectors>
        <igsn:samplingMethod>bucket</igsn:samplingMethod>
        <igsn:samplingCampaign>Campaign X</igsn:samplingCampaign>
        <igsn:relatedResources>
            <igsn:relatedResourceIdentifier>abcd1234</igsn:relatedResourceIdentifier>
        </igsn:relatedResources>
        <igsn:logElement event="submitted" timeStamp="2015-09-10T18:20:30" />
	</igsn:sample>
</igsn:samples>


<!--
cvc-complex-type.2.4.a: Invalid content was found starting with element 'igsn:curator'.
One of '{"http://igsn.org/schema/kernel-v.1.0":curation}' is expected.

cvc-complex-type.2.4.b: The content of element 'igsn:renderers' is not complete.
One of '{
	"http://igsn.org/schema/kernel-v.1.0":otherNames,
	"http://igsn.org/schema/kernel-v.1.0":classification,
	"http://igsn.org/schema/kernel-v.1.0":purpose,
	"http://igsn.org/schema/kernel-v.1.0":samplingFeatures,
	"http://igsn.org/schema/kernel-v.1.0":sampleCollectors,
	"http://igsn.org/schema/kernel-v.1.0":samplingMethod,
	"http://igsn.org/schema/kernel-v.1.0":samplingCampaign,
	"http://igsn.org/schema/kernel-v.1.0":relatedResources,
	"http://igsn.org/schema/kernel-v.1.0":comments,
	"http://igsn.org/schema/kernel-v.1.0":logElement}'
is expected.


-->

=== GeoscienceAustralia/samples-api/test/sample_eg4_IGSN_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<igsn:samples
		xsi:schemaLocation="http://igsn.org/schema/kernel-v.1.0 ../xml-validation/igsn-csiro-v2.0.xsd"
		xmlns:igsn="http://igsn.org/schema/kernel-v.1.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <igsn:sampleNumber>The dog and the hog</igsn:sampleNumber>
  <igsn:sampleName>The dog and the hog</igsn:sampleName>
  <igsn:isPublic>0</igsn:isPublic>
  <igsn:landingPage>http://eg.com</igsn:landingPage>
  <igsn:sampleTypes>
    <igsn:sampleType>None</igsn:sampleType>
  </igsn:sampleTypes>
  <igsn:materialTypes>
    <igsn:materialType>None</igsn:materialType>
  </igsn:materialTypes>
  <igsn:samplingLocation>AUS</igsn:samplingLocation>
  <igsn:samplingTime>None</igsn:samplingTime>
  <igsn:sampleCuration>x</igsn:sampleCuration>
  <igsn:curation>x</igsn:curation>
  <igsn:curator>x</igsn:curator>
  <igsn:curationLocation>GA shed</igsn:curationLocation>
  <igsn:classification>x</igsn:classification>
  <igsn:comments>x</igsn:comments>
  <igsn:otherNames>
    <igsn:otherName>x</igsn:otherName>
  </igsn:otherNames>
  <igsn:purpose>x</igsn:purpose>
  <igsn:samplingFeatures>
    <igsn:samplingFeature>None</igsn:samplingFeature>
  </igsn:samplingFeatures>
  <igsn:sampleCollectors>
    <igsn:sampleCollector>x</igsn:sampleCollector>
  </igsn:sampleCollectors>
  <igsn:samplingMethod>None</igsn:samplingMethod>
  <igsn:samplingCampaign>x</igsn:samplingCampaign>
  <igsn:relatedResources>
    <igsn:relatedResource>x</igsn:relatedResource>
  </igsn:relatedResources>
  <igsn:logEvent timeStamp="2015-09-10T18:20:30" event="submitted"/>
</igsn:sample>
